![Texto](https://dadosaocubo.com/wp-content/uploads/2020/06/DADOS-AO-CUBO-Vers%C3%A3o-04-1.png) 

#**Algebra Linear com Numpy**

POST: [Algebra Linear com Numpy](https://dadosaocubo.com/algebra-linear-com-numpy/)

### 1. Carregar biblioteca Numpy e gerar dados aleatórios

O método random.randint gera números inteiros pseudo-aleatórios enquanto o método random.rand gera números do tipo ponto flutuante (*float*).

Vamos inicializar a semente (*seed*) dos números aleatórios com o número 42.

In [ ]:
import numpy as np

np.random.seed(42)

In [ ]:
 
a

array([[4, 8, 8],
       [3, 6, 5],
       [2, 8, 6]])

In [ ]:
b = np.random.randint(low=1, high=10, size=(3,3))
b

array([[2, 5, 1],
       [6, 9, 1],
       [3, 7, 4]])

In [ ]:
c = np.random.randint(low=1, high=10, size=(5))

### 2. Operações com matrizes

A adição (+) e subtração (-) são feitas elemento a elemento. As duas matrizes precisam ter as mesmas dimensões.

In [ ]:
a+b

array([[ 6, 13,  9],
       [ 9, 15,  6],
       [ 5, 15, 10]])

In [ ]:
a-b

array([[ 2,  3,  7],
       [-3, -3,  4],
       [-1,  1,  2]])

A multiplicação escalar de matrizes também é feito elemento a elemento. As duas matrizes precisam ter as mesmas dimensões.

In [ ]:
a*b

Já o produto interno (*dot product* ) é feito entre matrizes de tamanho m x k e k x n e resulta numa matriz m x n. Ele é feito multiplicando linha a linha com coluna a coluna. É importante perceber que AB é diferente de BA.

In [ ]:
np.dot(a,b)

array([[ 80, 148,  44],
       [ 57, 104,  29],
       [ 70, 124,  34]])

In [ ]:
np.dot(b,a)

array([[ 25,  54,  47],
       [ 53, 110,  99],
       [ 41,  98,  83]])

A multiplicação por um escalar retorna cada elemento da matriz multiplicado por esse escalar.

In [ ]:
5*a

array([[20, 40, 40],
       [15, 30, 25],
       [10, 40, 30]])

Para obter a inversa, utiliza-se técnicas como a **Eliminação de Gauss**.

In [ ]:
np.linalg.inv(a) 

array([[-0.25,  1.  , -0.5 ],
       [-0.5 ,  0.5 ,  0.25],
       [ 0.75, -1.  , -0.  ]])

Para obter a transposta, basta inverter as linhas com colunas, no Numpy isso é feito acessando o atributo T.

In [ ]:
a.T

array([[4, 3, 2],
       [8, 6, 8],
       [8, 5, 6]])

### 3. Fatiamento (Slices)

*Slices* são fatias dos arrays (vetores ou matrizes). O fatiamento pode ser executado tanto *row-wise* (por linha) quanto *column-wise *(por coluna). O mais comum é por linha.

No exemplo abaixo, ao chamar o elemento 0 vai me retornar a primeira linha da matriz. Caso eu chame o elemento 0 de um vetor c ele vai me retornar o primeiro elemento (escalar).

In [ ]:
a[0]

array([4, 8, 8])

In [ ]:
c[0]

9

No próximo exemplo, vamos acessar as colunas da matriz. Eu peço o elemento da linha 2 e coluna 2 (lembrando que o indice começa em 0). Vai me retornar um escalar. Lembrando que pode-se usar duas sintaxes diferentes para isso, tanto A[X][Y] quanto A[X, Y].

In [ ]:
a[2][2]

6

In [ ]:
a[2,2]

6

Agora vamos observar a utilização dos dois-pontos (:). Ele serve pra me retornar um intervalo de valores. Se eu chamo a[:1] eu to pedindo pra me retornar do elemento 0 até o elemento y-1, no caso 1-1 = 0. Então ele me retorna o elemento da posição 0, o que é o mesmo que fazer a[0].

In [ ]:
a[:1]

array([[4, 8, 8]])

Se eu peço a[:2] vai me retornar do elemento 0 até o elemento 1 (2-1=1).

In [ ]:
a[:2]

array([[4, 8, 8],
       [3, 6, 5]])

Já se eu peço a[2:] vai me retornar do elemento 2 até o elemento n-1 (que é igual a 2), onde n é o tamanho da linha ou coluna pedida.

In [ ]:
a[2:]

array([[2, 8, 6]])

Se utilizar o menos (-), ele vai retornar na ordem inversa. Se eu tentar acessar o elemento -1 ele vai me retornar o último elemento.

In [ ]:
a[-1]

array([2, 8, 6])

Se eu pedir a[:-2] ele vai me retornar do elemento 0 até menos os dois últimos elementos.

In [ ]:
a[:-2]

array([[4, 8, 8],
       [3, 6, 5]])

Já se eu pedir a[-2:] ele vai me retornar 2 elementos até último elemento (n-1).

In [ ]:
a[-2:]

array([[3, 6, 5],
       [2, 8, 6]])

Eu posso também dizer de onde até onde eu quero. Se eu fizer a[1:3] ele vai retornar do elemento 1 até o elemento y-1 (3-1=2). Então vai me retornar o elemento 1 e o elemento 2.

In [ ]:
a[1:3]

array([[3, 6, 5],
       [2, 8, 6]])

Por último, podemos acessar os elementos por coluna com o operador dois-pontos (:) sem nenhum argumento. Quando eu chamo a[:,1] estou dizendo pra me retornar todos os elementos da coluna 1. Todas as operações mostradas são válidas também nesse modo.

In [ ]:
a[:,1]

array([8, 6, 8])

### **Fim.**


![42](https://upload.wikimedia.org/wikipedia/commons/5/56/Answer_to_Life.png)